version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Inlaze2023
    ports:
      - 54320:5432
  app:
    image: inlaze-back-db-1
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
